apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-cron
  namespace: argocd #This should be wherever your ArgoCD instance is running
  finalizers: #Finalizers are going to cause you some heartbreak; but they are useful if you wants cascading deletes
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default #Projects are just logical groupings of ArgoCD Applications; Also provide the ability to apply some RBAC around who can see what inside of ArgoCD.

  source:
    repoURL: https://github.com/tylerauerbeck/argocd-example.git
    targetRevision: master 
    path: manifests

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: tyler-test 

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

